stages:
  - 'preparation'
  # Test just one basic build, if it succeeds proceed to test the rest
  - 'build'
  - 'test'
  # Run multiple builds and tests, multi-distro, multi-arch
  - 'full builds'
  - 'full tests'

variables:
  CERBERO_IMAGE: 'registry.freedesktop.org/gstreamer/gst-ci/amd64/cerbero-fedora:fb5e6c259536f2733ac2901f04fffffb35c510b5'
  FEDORA_IMAGE: 'registry.freedesktop.org/gstreamer/gst-ci/amd64/fedora:b8c24cc7f4cfb19813a324cbbb65c5e89b55eebc'
  ANDROID_IMAGE: 'registry.freedesktop.org/gstreamer/gst-ci/amd64/ubuntu:b16ec7445ff7874d905eb5759ceaee5f93d29e66'
  INDENT_IMAGE: 'registry.freedesktop.org/gstreamer/gst-ci/amd64/gst-indent:6f7e01e1e30a73efa880acdc8e911f1f20c58dbb'
  MANIFEST_IMAGE: 'registry.freedesktop.org/gstreamer/gst-ci/amd64/build-manifest:d19082b72667fb3382bdc3621520c4d26e258b2e'

  GIT_STRATEGY: none
  DEFAULT_MESON_ARGS: >
    --werror
    -Dpython=enabled
    -Dlibav=enabled
    -Dugly=enabled
    -Dbad=enabled
    -Ddevtools=enabled
    -Dges=enabled
    -Drtsp_server=enabled
    -Dvaapi=enabled
    -Dsharp=disabled

  DEFAULT_CERBERO_ARGS: >
     --variants werror

manifest:
  image: $MANIFEST_IMAGE
  stage: 'preparation'
  script:
    - cd /gst-ci
    - gitlab/build_manifest.py --self-update
    - gitlab/build_manifest.py ${CI_PROJECT_DIR}/manifest.xml
    - cat ${CI_PROJECT_DIR}/manifest.xml
  artifacts:
    expire_in: "7 days"
    paths:
      - "manifest.xml"

gst indent:
  image: $INDENT_IMAGE
  stage: 'preparation'
  variables:
    GIT_STRATEGY: 'fetch'
  script:
    # man indent. grep RETURN VALUE, grab a beer on my behalf...
    - indent --version || true
    - curl -o gst-indent https://gitlab.freedesktop.org/gstreamer/gstreamer/raw/master/tools/gst-indent
    - chmod +x gst-indent
    - find . -name '*.c' -exec ./gst-indent {} +
    - |
      if git diff --quiet; then
          echo "Code is properly formatted"
      else
          git diff --color=always
          echo 'style diverges, please run gst-indent first'
          exit 1
      fi
  except:
    variables:
      # No point on trying to format C files in those repositories
      - $CI_PROJECT_NAME == "gstreamer-sharp"
      - $CI_PROJECT_NAME == "cerbero"

.build:
  stage: 'full builds'
  dependencies:
    - "manifest"
  variables:
    CC: "ccache gcc"
    CXX: "ccache g++"
    CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
    MAIN_DIR: "${CI_PROJECT_DIR}/validate-output/"
    MESON_ARGS: "${DEFAULT_MESON_ARGS}"

  script:
    - ccache -z
    # Not sure why, but permission errors else
    # https://gitlab.freedesktop.org/alatiera/gstreamer/-/jobs/41441
    - cp -r /gst-build/ . && cd gst-build
    - ./git-update --no-interaction --manifest="${CI_PROJECT_DIR}/manifest.xml"
    - meson build/ $MESON_ARGS
    - ninja -C build/
    - ccache -s
  after_script:
    - cd gst-build/
    # Clean the artifacts packages to avoid copying "useless" build products.
    - test -d build && find build -name '*.[ao]' -delete
    # Clean the .git repos since we won't need them anymore
    - rm -rf subprojects/*/.git/
    - rm -rf build/subprojects/*/.git/
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - "${CCACHE_DIR}"
  artifacts:
    expire_in: '5 days'
    when: always
    paths:
      - "manifest.xml"
      - "gst-build/"
  except:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

build fedora x86_64:
  extends: '.build'
  stage: 'build'
  image: $FEDORA_IMAGE
  variables:
    MESON_ARGS: "${DEFAULT_MESON_ARGS} -Dsharp=enabled"

build android arm64 api28:
  extends: '.build'
  image: $ANDROID_IMAGE
  variables:
    MESON_ARGS: >
      -Dbad=enabled
      -Dbad:androidmedia=enabled
      --cross-file cross-files/android_arm64_api28.txt

.test:
  stage: 'test'
  variables:
    MAIN_DIR: "${CI_PROJECT_DIR}/validate-output/"
    # Disable colored output to avoid weird rendering issues
    GST_DEBUG_COLOR: 'no'

    # note the -b at the start of each line
    # Can't comment inline sadly
    # FIXME: get this into gst-validate-launcher KNOWN_ISSUES
    # gstreamer.pipelines_parse_launch.delayed_link: https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/345
    # gstreamer.gst_gstsystemclock.test_async_sync_interaction: https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/346
    # gstreamer.gst_gstsystemclock.test_periodic_multi: https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/347
    # gstreamer.gst_gstsystemclock.test_periodic_shot: https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/348
    # elements_multisocketsink.test_sending_buffers_with_9_gstmemories: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/525
    # elements_multisocketsink.test_client_next_keyframe: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/516
    # flvmux.test_incrementing_timestamps: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/530
    # flvmux.test_video_caps_late: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/543
    # rtpbin.test_sender_eos: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/527
    # rtpbin.test_cleanup_recv: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/546
    # souphttpsrc.test_icy_stream: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/307
    # rtspserver.test_shared_udp: https://gitlab.freedesktop.org/gstreamer/gst-rtsp-server/issues/61
    # rtpsession.test_multiple_senders_roundrobin_rbs: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/548
    # dtls: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/811
    # mpegtsmux.test_align: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/844
    # shm.test_shm_live: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/847
    # splitmux.test_splitmuxsink_async: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/531
    # splitmux.test_splitmuxsrc_caps_change: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/547
    # splitmux.test_splitmuxsrc_sparse_streams: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/issues/544
    # netsim.netsim_stress: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/849
    # nle_complex.test_one_expandable_another: https://gitlab.freedesktop.org/gstreamer/gst-editing-services/issues/55
    # nle_simple.test_simplest: https://gitlab.freedesktop.org/gstreamer/gst-editing-services/issues/57
    # ges_basic.test_ges_pipeline_change_state: https://gitlab.freedesktop.org/gstreamer/gst-editing-services/issues/58
    # gst-editing-services.pythontests.pyunittest.python.test_timeline.TestTransitions.test_transition_type: https://gitlab.freedesktop.org/gstreamer/gst-editing-services/issues/62
    # gst-editing-services.pythontests.pyunittest.python.test_timeline.TestTransitions.test_auto_transition: https://gitlab.freedesktop.org/gstreamer/gst-editing-services/issues/63
    # pipelines_tcp.test_that_tcpserversink_and_tcpclientsrc_are_symmetrical: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/221
    # elements_capsfilter.test_unfixed_downstream_caps: https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/335
    # gst_rtspclientsink.test_record: https://gitlab.freedesktop.org/gstreamer/gst-rtsp-server/issues/55
    # elements_audiotestsrc.test_layout: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/535
    # camerabin.test_image_video_cycle: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/864
    # camerabin.test_single_video_recording: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/864#note_101558
    # camerabin.test_multiple_video_recordings: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/864#note_101646
    # audiomixer.test_flush_start_flush_stop: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/555
    # check.gstreamer-sharp.SdpTests: https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/17
    #
    # TO FURTHER INVESTIGATE:
    # check.gst-plugins-base.libs_gstglcolorconvert.test_reorder_buffer
    # check.gstreamer.gst_gstelement.test_foreach_pad
    # check.gstreamer.libs_baseparse.parser_pull_short_read
    # check.gstreamer.pipelines_seek.test_loopback_2
    # check.gst-plugins-base.elements_appsrc.test_appsrc_blocked_on_caps
    BLACKLIST: >
      -b check.gstreamer.pipelines_parse_launch.delayed_link
      -b check.gstreamer.gst_gstsystemclock.test_async_sync_interaction
      -b check.gstreamer.gst_gstsystemclock.test_periodic_multi
      -b check.gstreamer.gst_gstsystemclock.test_periodic_shot
      -b check.gstreamer.pipelines_seek.test_loopback_2
      -b check.gstreamer.gst_gstelement.test_foreach_pad
      -b check.gstreamer.libs_baseparse.parser_pull_short_read
      -b check.gst-plugins-base.elements_multisocketsink.test_sending_buffers_with_9_gstmemories
      -b check.gst-plugins-base.elements_multisocketsink.test_client_next_keyframe
      -b check.gst-plugins-base.elements_multisocketsink.test_add_client
      -b check.gst-plugins-base.libs_gstglcolorconvert.test_reorder_buffer
      -b check.gst-plugins-base.elements_audiotestsrc.test_layout
      -b check.gst-plugins-good.elements_souphttpsrc.test_icy_stream
      -b check.gst-plugins-good.elements_rtpbin.test_sender_eos
      -b check.gst-plugins-good.elements_rtpbin.test_cleanup_recv
      -b check.gst-plugins-good.elements_flvmux.test_incrementing_timestamps
      -b check.gst-plugins-good.elements_flvmux.test_video_caps_late
      -b check.gst-plugins-base.elements_appsrc.test_appsrc_blocked_on_caps
      -b check.gst-plugins-good.elements_splitmux.test_splitmuxsrc_sparse_streams
      -b check.gst-plugins-good.elements_splitmux.test_splitmuxsrc_caps_change
      -b check.gst-plugins-bad.elements_dtls.test_data_transfer
      -b check.gst-plugins-bad.elements_dtls.test_create_and_unref
      -b check.gst-plugins-bad.elements_camerabin.test_image_video_cycle
      -b check.gst-plugins-bad.elements_camerabin.test_single_video_recording
      -b check.gst-plugins-bad.elements_camerabin.test_multiple_video_recordings
      -b check.gst-plugins-good.elements_rtpsession.test_multiple_senders_roundrobin_rbs
      -b check.gst-plugins-bad.elements_shm.test_shm_live
      -b check.gst-plugins-good.elements_splitmux.test_splitmuxsink_async
      -b check.gst-plugins-bad.elements_netsim.netsim_stress
      -b check.gst-editing-services.nle_complex.test_one_expandable_another
      -b check.gst-editing-services.nle_simple.test_simplest
      -b check.gst-editing-services.ges_basic.test_ges_pipeline_change_state
      -b check.gst-editing-services.pythontests.pyunittest.python.test_timeline.TestTransitions.test_transition_type
      -b check.gst-editing-services.pythontests.pyunittest.python.test_timeline.TestTransitions.test_auto_transition
      -b check.gst-plugins-base.pipelines_tcp.test_that_tcpserversink_and_tcpclientsrc_are_symmetrical
      -b check.gstreamer.elements_capsfilter.test_unfixed_downstream_caps
      -b check.gst-rtsp-server.gst_rtspclientsink.test_record
      -b check.gst-rtsp-server.gst_rtspserver.test_shared_udp
      -b check.gst-plugins-base.elements_audiomixer.test_flush_start_flush_stop
      -b check.gstreamer-sharp.SdpTests
  script:
    - cd gst-build/
    - >
      ./gst-uninstalled.py
      gst-validate-launcher ${TEST_SUITE}
      -fs
      --mute
      --shuffle
      --no-display
      --dump-on-failure
      --meson-no-rebuild
      -M "${CI_PROJECT_DIR}/validate-output/"
      --xunit-file "${CI_PROJECT_DIR}/validate-output/logs/xunit.xml"
      ${BLACKLIST}
  artifacts:
    expire_in: '14 days'
    when: always
    paths:
      - 'gst-build/build/meson-logs/'
      - 'validate-output/logs'
    reports:
      junit:
        - "validate-output/logs/*.xml"
  # We disable the .build above, which this job usually depends upon for cerbero
  except:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

.test fedora x86_64:
  image: $FEDORA_IMAGE
  extends: '.test'
  dependencies:
    - build fedora x86_64

check fedora:
  extends: '.test fedora x86_64'
  variables:
    TEST_SUITE: "check.gst*"

# Template for Cerbero GStreamer Build
#
# Parameters:
# CONFIG: The name of the configuration file to use
#
# Produces runtime and devel tarball packages.
.cerbero:
  stage: "full builds"
  image: $CERBERO_IMAGE
  dependencies:
    - "manifest"
  variables:
    CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
    CCACHE_MAXSIZE: "1.7G"
    CERBERO_HOME: "${CI_PROJECT_DIR}/cerbero-build"
    CERBERO_SOURCES: "${CI_PROJECT_DIR}/cerbero-sources"
    CERBERO_DEPS: "cerbero-deps.tar.gz"
    CERBERO_ARGS: "${DEFAULT_CERBERO_ARGS}"
    CERBERO: "./cerbero-uninstalled -c config/${CONFIG} -c localconf.cbc -m manifest.xml"
  before_script:
    # FIXME Wrong namespace
    # Workaround build-tools having hardcoded internal path
    - mkdir -p /builds/gstreamer
    - ln -sf ${CI_PROJECT_DIR} /builds/gstreamer/cerbero
    - rsync -aH /cerbero/ .
    - test -f ${CERBERO_DEPS} && tar -C ${CERBERO_HOME} -xf ${CERBERO_DEPS}
    - echo "home_dir = \"${CERBERO_HOME}\"" >> localconf.cbc
    - echo "local_sources = \"${CERBERO_SOURCES}\"" >> localconf.cbc
    - ./cerbero-uninstalled --self-update manifest.xml
    - ccache -z
  script:
    - $CERBERO $CERBERO_ARGS show-config
    - $CERBERO $CERBERO_ARGS fetch-bootstrap --build-tools-only
    - $CERBERO $CERBERO_ARGS fetch-package --deps gstreamer-1.0
    - $CERBERO $CERBERO_ARGS fetch-cache
    - $CERBERO $CERBERO_ARGS bootstrap --offline --build-tools-only
    - $CERBERO $CERBERO_ARGS package --offline -t -o ${CI_PROJECT_DIR} gstreamer-1.0
    - ccache -s
  except:
    variables:
      - $CI_PROJECT_NAME == "gst-build"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - "${CCACHE_DIR}"
      - "${CERBERO_SOURCES}"
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: '5 days'
    when: 'always'
    paths:
      - "manifest.xml"
      - "cerbero-build/logs"
      - "*.tar.bz2"

# Template for Cerbero GStreamer Deps
#
# This template is used by cerbero/ project to pre-built the GStreamer
# depedencies. When available, the .cerbero jobs will download this artifact
# in order to speed up the build.
#
# Parameters:
# CONFIG: The name of the configuration file to use
# ARCH: The cerbero <os>_<cpu> (used in cache key)
#
# Produce an artifact with the dist/ and .cache along
# with the associated build-tools.
.cerbero deps:
  extends: .cerbero
  stage: "build"
  script:
    - $CERBERO $CERBERO_ARGS show-config
    - $CERBERO $CERBERO_ARGS fetch-bootstrap --build-tools-only
    - $CERBERO $CERBERO_ARGS fetch-package --deps gstreamer-1.0
    - $CERBERO $CERBERO_ARGS bootstrap --offline --build-tools-only
    - $CERBERO $CERBERO_ARGS build-deps --offline
          gstreamer-1.0 gst-plugins-base-1.0 gst-plugins-good-1.0
          gst-plugins-bad-1.0 gst-plugins-ugly-1.0 gst-rtsp-server-1.0
          gst-libav-1.0 gst-validate gst-editing-services-1.0 libnice
    - $CERBERO $CERBERO_ARGS fetch-cache --skip-fetch --job-id=${CI_JOB_ID}
    - tar -C ${CERBERO_HOME} -czf $CERBERO_DEPS
              build-tools build-tools.cache
              dist/${ARCH} ${ARCH}.cache
    - ccache -s
  only:
    variables:
      - $CI_PROJECT_NAME == "cerbero"
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: '10 days'
    when: 'always'
    paths:
      - "manifest.xml"
      - "cerbero-build/logs"
      - "cerbero-build/cerbero-deps.log"
      - "${CERBERO_DEPS}"

#
# Cerbero Linux X86_64 build
#
cerbero deps fedora x86_64:
  extends: '.cerbero deps'
  variables:
    CONFIG: "linux.config"
    ARCH: "linux_x86_64"

.cerbero fedora x86_64:
  extends: '.cerbero'
  variables:
    CONFIG: "linux.config"

cerbero fedora x86_64:
  extends: '.cerbero fedora x86_64'
  dependencies:
    - "cerbero deps fedora x86_64"
  only:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

build cerbero fedora x86_64:
  extends: '.cerbero fedora x86_64'
  except:
    variables:
      - $CI_PROJECT_NAME == "cerbero"


#
# Cerbero Cross Windows builds
#
cerbero deps windows x86:
  extends: '.cerbero deps'
  variables:
    CONFIG: "cross-win32.cbc"
    ARCH: "windows_x86"

.cerbero cross win32:
  extends: '.cerbero'
  variables:
    CONFIG: "cross-win32.cbc"

cerbero cross win32:
  extends: '.cerbero cross win32'
  dependencies:
    - "cerbero deps windows x86"
  only:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

build cerbero cross win32:
  extends: '.cerbero cross win32'
  except:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

cerbero deps windows x86_64:
  extends: '.cerbero deps'
  variables:
    CONFIG: "cross-win64.cbc"
    ARCH: "windows_x86_64"

.cerbero cross win64:
  extends: '.cerbero'
  variables:
    CONFIG: "cross-win64.cbc"

cerbero cross win64:
  extends: '.cerbero cross win64'
  dependencies:
    - "cerbero deps windows x86_64"
  only:
    variables:
      - $CI_PROJECT_NAME == "cerbero"

build cerbero cross win64:
  extends: '.cerbero cross win64'
  except:
    variables:
      - $CI_PROJECT_NAME == "cerbero"
